# Generated by Django 5.2.5 on 2025-09-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
