# Generated by Django 5.2.5 on 2025-09-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('day', models.CharField(max_length=10)),
                ('unit', models.IntegerField()),
                ('room', models.CharField(max_length=10)),
            ],
        ),
    ]
